// --- HERO PRESET DEFINITION ---
// NOTE: Optics calibration values in K1_HERO_PRESET are generated by
// tools/python/calibration/calibrate_optics.py in the SpectraSynq.LandingPage repo.
// This repo only consumes the JSON output; the tool itself lives elsewhere.

/*
  RAW CALIBRATION DATA (Prototype #X Optical Fingerprint - 2025-12-01)
  --------------------------------------------------------------------
  Asymmetric values likely due to physical assembly variances (film cut/bowing)
  and camera perspective. Preserved here for hardware iteration reference.

  "topSpreadNear": 0.0411,
  "topSpreadFar": 0.0573,
  "bottomSpreadNear": 0.1000,
  "bottomSpreadFar": 0.0506,
  "topFalloff": 1.4029,
  "bottomFalloff": 3.8216,
  "columnBoostStrength": 0.0,
  "columnBoostExponent": 1.2,
  "edgeHotspotStrength": 5.0,
  "edgeHotspotWidth": 0.1
*/

export const K1_HERO_PRESET = {
  visuals: {
    exposure: 4.0,
    baseLevel: 0.0,
    tint: '#ffffff',
  },
  optics: {
    // SYMMETRIZED DESIGN-INTENT VALUES (Averaged from calibration)
    // Top: Sharp ribs
    topSpreadNear: 0.0706,
    topSpreadFar: 0.0539,
    topFalloff: 2.61,

    // Bottom: Soft domes
    bottomSpreadNear: 0.0706,
    bottomSpreadFar: 0.0539,
    bottomFalloff: 2.61,

    // Interaction
    columnBoostStrength: 0.0,
    columnBoostExponent: 1.2,

    // Mechanical
    edgeHotspotStrength: 5.0,
    edgeHotspotWidth: 0.1,
  },
  physics: {
    motionMode: 'Center Origin',
    simulationSpeed: 1.0,
    decay: 0.15,
    ghostAudio: true,
  },
};
